### ISSUE TITLE
Work around for upgrading to flutter_stripe_payment 1.1.4 for flutter 1.22.6

### ISSUE THREAD

**Issue by dominic-do** [jonasbark/flutter_stripe_payment#322]
Hi,
We are having this email from Google Play Store:
**We found your app is using a non-compliant version of Stripe SDK which facilitates the transmission of collection of users’ installed packages information without meeting the prominent disclosure guidelines and/or privacy policy guidelines. If necessary, you can consult your SDK provider(s) for further information.**

I understand that the latest version of flutter_stripe_payment will fix this issue. However, we are using the Version 1.0.11 on Flutter 1.22.6, we can't use the latest version (1.1.4) because it's using Dart 2.12 which uses flutter 2. Any workaround to how to overcome this issue without having to upgrade to flutter 2?

Thank you so much.

**Comment by soarHero** [comment]
You can try

```

stripe_payment:
    git:
      url: https://github.com/soarHero/flutter_stripe_payment.git
      ref: 52fff88d8986cd6c6a8fe3ec70472fdd8c511bd9
```

I removed the "null safety" code and can be used for Flutter 1.22.
